project:
  title: "Schrodinger's Equation"
  render:
    - "*.qmd"

execute:
  cache: true

format:
  html:
    toc: false
  pdf:
    include-in-header:
      - text: |
          \usepackage{braket}
    toc: false
  ipynb:
    toc: false
